"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { Navigation } from "../components/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  function topScroll() {
    window.scrollTo(0, 0);
  }

  return (
    <html lang="en">
      <head>
      <title>Pokedex App</title>
      </head>
      <body>
        {/* <Navigation /> */}
        {children}
        <div
          onClick={topScroll}
          className="sticky w-12 h-12 px-2 py-4 flex justify-center items-center bg-white rounded-lg float-right bottom-10 right-10 cursor-pointer"
        >
          <img
            className="w-10"
            src="https://js-pokedex-virid.vercel.app/src/arrow-up-icon.png"
            alt=""
          />
        </div>
      </body>
    </html>
  );
}
/* 
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Document</title>
</head>
<body>
  
</body>
</html> */